const BankDB = [
  {
    id: 1,
    code: 'ACB',
    name: 'Ngân hàng TMCP Á Châu',
    logo: 'ACB.jpg',
  },
  {
    id: 2,
    code: 'TPBANK',
    name: 'Ngân hàng TMCP Tiên Phong',
    logo: 'TPBANK.jpg',
  },
  {
    id: 3,
    code: 'DAB',
    name: 'Ngân hàng TMCP Đông Á',
    logo: 'DAB.jpg',
  },
  {
    id: 4,
    code: 'SEABANK',
    name: 'Ngân Hàng TMCP Đông Nam Á',
    logo: 'SEABANK.jpg',
  },
  {
    id: 5,
    code: 'ABBANK',
    name: 'Ngân hàng TMCP An Bình',
    logo: 'ABBANK.jpg',
  },
  {
    id: 6,
    code: 'BACABANK',
    name: 'Ngân hàng TMCP Bắc Á',
    logo: 'BACABANK.jpg',
  },
  {
    id: 7,
    code: 'VIETCAPITALBANK',
    name: 'Ngân hàng TMCP Bản Việt',
    logo: 'VIETCAPITALBANK.jpg',
  },
  {
    id: 8,
    code: 'MSB',
    name: 'Ngân hàng TMCP Hàng hải Việt Nam',
    logo: 'MSB.jpg',
  },
  {
    id: 9,
    code: 'TCB',
    name: 'Ngân hàng TMCP Kỹ Thương Việt Nam',
    logo: 'TCB.jpg',
  },
  {
    id: 12,
    code: 'NCB',
    name: 'Ngân hàng TMCP Quốc Dân',
    logo: 'NCB.jpg',
  },
  {
    id: 18,
    code: 'VIB',
    name: 'Ngân hàng TMCP Quốc tế Việt Nam',
    logo: 'VIB.jpg',
  },
  {
    id: 19,
    code: 'SCB',
    name: 'Ngân hàng TMCP Sài Gòn',
    logo: 'SCB.jpg',
  },
  {
    id: 21,
    code: 'SHB',
    name: 'Ngân hàng TMCP Sài Gòn – Hà Nội',
    logo: 'SHB.jpg',
  },
  {
    id: 22,
    code: 'STB',
    name: 'Ngân hàng TMCP Sài Gòn Thương Tín',
    logo: 'STB.jpg',
  },
  {
    id: 23,
    code: 'VAB',
    name: 'Ngân hàng TMCP Việt Á',
    logo: 'VAB.jpg',
  },
  {
    id: 24,
    code: 'BVB',
    name: 'Ngân hàng TMCP Bảo Việt',
    logo: 'BVB.jpg',
  },
  {
    id: 25,
    code: 'VIETBANK',
    name: 'Ngân hàng TMCP Việt Nam Thương Tín',
    logo: 'VIETBANK.jpg',
  },
  {
    id: 27,
    code: 'EIB',
    name: 'Ngân Hàng TMCP Xuất Nhập khẩu Việt Nam',
    logo: 'EIB.jpg',
  },
  {
    id: 28,
    code: 'LPB',
    name: 'Ngân Hàng TMCP Bưu điện Liên Việt',
    logo: 'LPB.jpg',
  },
  {
    id: 29,
    code: 'VCB',
    name: 'Ngân Hàng TMCP Ngoại thương Việt Nam',
    logo: 'VCB.jpg',
  },
  {
    id: 30,
    code: 'CTG',
    name: 'Ngân Hàng TMCP Công Thương Việt Nam',
    logo: 'CTG.jpg',
  },
  {
    id: 31,
    code: 'BIDV',
    name: 'Ngân Hàng TMCP Đầu tư và Phát triển Việt Nam',
    logo: 'BIDV.jpg',
  },
  {
    id: 32,
    code: 'VBSP',
    name: 'Ngân hàng Chính sách xã hội',
    logo: 'VBSP.jpg',
  },
  {
    id: 14,
    code: 'HDBANK',
    name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh',
    logo: 'HDBANK.png',
  },
  {
    id: 10,
    code: 'KIENLONGBANK',
    name: 'Ngân hàng TMCP Kiên Long',
    logo: 'KIENLONGBANK.png',
  },
  {
    id: 16,
    code: 'MB',
    name: 'Ngân hàng TMCP Quân đội',
    logo: 'MB.png',
  },
  {
    id: 11,
    code: 'NAMABANK',
    name: 'Ngân hàng TMCP Nam Á',
    logo: 'NAMABANK.png',
  },
  {
    id: 15,
    code: 'OCB',
    name: 'Ngân hàng TMCP Phương Đông',
    logo: 'OCB.png',
  },
  {
    id: 26,
    code: 'PGBANK',
    name: 'Ngân Hàng TMCP Xăng Dầu Petrolimex',
    logo: 'PGBANK.png',
  },
  {
    id: 17,
    code: 'PVCOMBANK',
    name: 'Ngân hàng TMCP Đại chúng',
    logo: 'PVCOMBANK.png',
  },
  {
    id: 13,
    code: 'VPBANK',
    name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    logo: 'VPBANK.png',
  },
  {
    id: 20,
    code: 'SGB',
    name: 'Ngân hàng TMCP Sài Gòn Công Thương',
    logo: 'SGB.jpg',
  },
  {
    id: 34,
    code: 'CB',
    name: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam',
    logo: 'CB.jpg',
  },
  {
    id: 35,
    code: 'OCEANBANK',
    name: 'Ngân hàng Thương mại TNHH MTV Đại Dương',
    logo: 'OCEANBANK.jpg',
  },
  {
    id: 36,
    code: 'GPBANK',
    name: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu',
    logo: 'GPBANK.jpg',
  },
  {
    id: 37,
    code: 'AGRIBANK',
    name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    logo: 'AGRIBANK.jpg',
  },
  {
    id: 33,
    code: 'VDB',
    name: 'Ngân hàng Phát triển Việt Nam',
    logo: 'VDB.png',
  },
]

export default BankDB
